### ISSUE TITLE
.NET SDK Not Found

### ISSUE THREAD

**Issue by ryleu** [PepeCitron/vintagestory-server#2]
I keep getting this error whenever I try to run the server:
```
vs_server  | Launching server...
vs_server  | The command could not be loaded, possibly because:
vs_server  |   * You intended to execute a .NET application:
vs_server  |       The application 'VintagestoryServer.dll' does not exist.
vs_server  |   * You intended to execute a .NET SDK command:
vs_server  |       No .NET SDKs were found.
vs_server  | 
vs_server  | Download a .NET SDK:
vs_server  | https://aka.ms/dotnet/download
vs_server  | 
vs_server  | Learn about SDK resolution:
vs_server  | https://aka.ms/dotnet/sdk-not-found
```

This is my docker-compose.yml:
```yml
version: "3.8"

services:
  vintage-story:
    container_name: vs_server
    image: pepecitron/vintagestory-server
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "42420:42420"
    volumes:
      - /mnt/game1/vintage-story:/data/server-file
    environment:
      SERVER_BRANCH: "stable"
      SERVER_VERSION: "1.19.8"
      SERVER_PORT: "42420"
      SERVER_NAME: "the land of our holy god mike"
      SERVER_DESCRIPTION: "mike's private vintage story server"
      SERVER_MOTD: "{0} tapped in!"
      SERVER_MAX_CLIENTS: "10"
      SERVER_PASSWORD: "redacted"
      SERVER_WHITELIST: false
      SERVER_PUBLIC: false
      #SERVER_SERVER_LANGUAGE: "en_US"
      SERVER_PVP: true
      SERVER_FIRE_SPREAD: true
```

Any ideas?
