### ISSUE TITLE
[HELP] How to configure serverconfig.json via ENV container 

### ISSUE THREAD

**Issue by Alexkill536ITA** [PepeCitron/vintagestory-server#8]
I'm trying to set the ENV variables but when I go into the serverconfig.json file I always find it regenerated with the default var. Can you give me an elucidation on how to configure it properly.

every time the container starts it resets my configs to default

```yaml
services:
  vintage-story:
    container_name: vintage-story
    image: "pepecitron/vintagestory-server:latest"
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "42420:42420"
    volumes:
      - vintage-story:/gamedata
    environment:
      TZ: "Europe/Rome"
      SERVER_BRANCH: "stable"
      SERVER_VERSION: "1.20.0"
      SERVER_NAME: "Server GDR ITALIANO del Tharfone"
      SERVER_DESCRIZIONE: "Server GDR ITALIANO per accedere passare da Discord https://discord.gg/3eSqS4hPYf"
      SERVER_WHITELIST: true
      SERVER_PUBLIC: true
      SERVER_SERVER_LANGUAGE: "it"
      SERVER_PVP: true
      SERVER_FIRE_SPREAD: false
     mem_limit: 4g

volumes:
  vintage-story:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: E:/Server Docker/vintage-story/gamedata
```
